### ISSUE TITLE
thats what happen when i run python3 checker.py -i CHAN

### ISSUE THREAD

**Issue by Houssam47** [drkostas/Youtube-FirstCommentBot#2]
([name]) C:\Users\HOUSSAM\Desktop\Youtube-First-Commenter-Bot-master>python checker.py -i CHANNEL_ID add
Starting..
Traceback (most recent call last):
  File "checker.py", line 117, in <module>
    main()
  File "checker.py", line 66, in main
    channel = youtube.get_channel_by_id(args.id)
  File "C:\Users\HOUSSAM\Desktop\Youtube-First-Commenter-Bot-master\youtubeapi.py", line 72, in get_channel_by_id
    return self.channel_from_response(channels_response)
  File "C:\Users\HOUSSAM\Desktop\Youtube-First-Commenter-Bot-master\youtubeapi.py", line 50, in channel_from_response
    for channel in response['items']:
KeyError: 'items'

**Comment by SwixDevs** [comment]
Did you fix that issue? Do you get the error "API limit reached, waiting for 100 seconds"? Please reply.

**Comment by Houssam47** [comment]
i did but i cant remember how lol.
for API you have to check google API maybe change it

**Comment by Houssam47** [comment]
the code is broken dont waste your time on that.

**Comment by SwixDevs** [comment]
So, you are not able to comment on every single video? Because I made a database, sql server, edited the code fully...is there anything I can do?

**Comment by Houssam47** [comment]
No you can't. This code can comment only youtube channels that you want.

**Comment by SwixDevs** [comment]
> @Houssam47 Thanks for the suggestion! I will consider implementing it if it doesn't require too many changes.
> I'll keep you posted.

That exact statement is on line 104 btw, and now when I run the program by "python checker.py", nothing happens, any reason to it?

**Comment by SwixDevs** [comment]
I forgot what you write to run a program? @drkostas

You type in Server/venv/Scripts/activate

and then when that (venv) comes in the cmd, you type in python checker.py

When I do that, the same path comes up where the file is located..

**Comment by SwixDevs** [comment]
Hey there! Thanks for your help, but it still does not work. As soon as I start the program, I get this:
"Starting..
Done! Waiting for new videos to be uploaded..
Error: Too many requests:
'items'
Waiting 100 seconds.." 
The program does not even comment anything, it just prints this when I start it. The same thing keeps repeating over and over again because of "time.sleep(100)". It comments nothing.

Are you aware of this issue, and are you working on it?
Thank you for your help.

Shaurya Juneja

**Comment by SwixDevs** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/57228989/84490466-d5ddc280-acc0-11ea-8c63-73578e5b3191.png)

**Comment by SwixDevs** [comment]
By the way, will you be willing to help me with an other bot? I am not a python programmer, so I am getting a problem in an other simple bot...it's here - https://github.com/ItsCEED/Youtube-Comment-Bot

**Comment by SwixDevs** [comment]
@drkostas  any help?

**Comment by ashok020** [comment]
![image](https://user-images.githubusercontent.com/61375148/115289449-3145d000-a170-11eb-9540-bc9f7df684a0.png)
