### ISSUE TITLE
getting error ' No module named 'youbot''

### ISSUE THREAD

**Issue by Mubashir-rehma** [drkostas/Youtube-FirstCommentBot#7]
I am trying to install the setup on my local machine with venv and 3.10 python version. I have updated all the required credentials like client id, client secret, youtube id, etc. But again getting the error, don't why. here is the command that I am getting error on running it.
`python youbot/run.py -c confs/generic.yml -l logs/generic.log -m remove_channel -i UCqVEz1Gl1mPQB7_Ee1BetRw`

This is the error

`Traceback (most recent call last):
  File "C:\Users\Marechal\Desktop\Project youtube comment\Youtube-FirstCommentBot-master\youbot\run.py", line 4, in <module>
    from youbot import Configuration, ColorLogger, YoutubeManager
ModuleNotFoundError: No module named 'youbot'
`

**Comment by drkostas** [comment]
Did you get any errors running the `make install` command? Can you double-check that you activated the conda environment before running the command?

**Comment by Mubashir-rehma** [comment]
Thank you so much for the response. I have activated the ` conda env`. and have also run `make install` command but again it shows the same error. Here are the results for each command.

**conda deactivate**
`E:\Webistes\Youtube-FirstCommentBot-master>doskey make=mingw32-make.exe`

**make install**
`C:/MinGW/bin/make clean
make[1]: Entering directory 'E:/Webistes/Youtube-FirstCommentBot-master'
'~' is not recognized as an internal or external command,
operable program or batch file.
Makefile:74: recipe for target 'clean' failed
make[1]: *** [clean] Error 1
make[1]: Leaving directory 'E:/Webistes/Youtube-FirstCommentBot-master'
Makefile:62: recipe for target 'install' failed
make: *** [install] Error 2`

**conda activate youbot**
`E:\Webistes\Youtube-FirstCommentBot-master>doskey make=mingw32-make.exe
Could not find conda environment: youbot
You can list all discoverable environments with `conda info --envs`.`

**conda info --envs**
`# conda environments:
#
base                  *  C:\Users\rmuba\anaconda3
`

**python youbot/run.py -c confs/generic.yml -l logs/generic.log -m add_channel -i ArynewsTvofficial**
`Traceback (most recent call last):
  File "E:\Webistes\Youtube-FirstCommentBot-master\youbot\run.py", line 4, in <module>
    from youbot import Configuration, ColorLogger, YoutubeManager
ModuleNotFoundError: No module named 'youbot'`

**Comment by drkostas** [comment]
Hi @Mubashir-rehma , I haven't tested it on Windows with Cygwin, that is the most probable reason for the error. Can you run the commands that `make install` is executing manually? Try running the following:

1. `python setup.py clean` (if it fails, ignore it)
1. `conda deactivate`
1. `conda env remove -n youbot`
1. `conda create -n youbot python=3.8 -y`
1. `conda activate youbot`
1. `pip install -r requirements.txt`
1.  `pip install setuptools`
1. `python setup.py install`

Let me know if that fixes the issue.
